# Generated by Django 6.0.2 on 2026-02-12 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_reservation', models.IntegerField()),
                ('movie_title', models.CharField(max_length=120)),
                ('room', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('available_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('seats', models.IntegerField()),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='reservado', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('show_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='cinema.show')),
            ],
        ),
    ]
